//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 12:11:17 AM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.packtpub.com/liverestaurant/OrderService/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.packtpub.liverestaurant.domain;
